// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class issuechangemaxlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(issuechangemaxlength));
        
        string IMigrationMetadata.Id
        {
            get { return "201605081746180_issue-change-maxlength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
