// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_isadmin_to_applicationuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isadmin_to_applicationuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201605161309427_add_isadmin_to_applicationuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
