// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class projectforeignkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(projectforeignkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201605021207508_project-foreign-key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
