// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeissuesfromproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeissuesfromproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201605082125246_remove-issues-from-project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
