// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_ids_everywhere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ids_everywhere));
        
        string IMigrationMetadata.Id
        {
            get { return "201605201653594_add_ids_everywhere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
